//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public int id_servicio { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tiempo { get; set; }
        public int id_usuario { get; set; }
        public Nullable<System.Guid> guid { get; set; }
    
        [Newtonsoft.Json.JsonIgnore] public virtual usuario usuario { get; set; }
    }
}
